DROP TABLE Users CASCADE;
DROP TABLE Credentials CASCADE ;
DROP TABLE Teams CASCADE ;
DROP TABLE Events CASCADE;
DROP TABLE EventTeams CASCADE;
DROP TABLE Matchs CASCADE;
DROP TABLE MatchScore CASCADE;


DROP DOMAIN USER_STATUS;
DROP DOMAIN DEPOT_STATUS;
DROP DOMAIN SCORE_STATUS;
DROP DOMAIN PASSWORD;
